# Taskfile.yml
version: '3'

tasks:
  build-blender-container:
    desc: "build blender container"
    dir: deployment/images/ubuntu-blender
    cmds:
      - docker build . -t flamenco-blender-base
  build-manager:
    desc: "build manager container"
    dir: deployment/images/manager
    cmds:
      - docker build . -t flamenco-manager
  build-worker:
    desc: "build worker container"
    dir: deployment/images/worker
    cmds:
      - echo "make sure network exists with  'docker network create test-network'"
      - docker build . -t flamenco-worker
  run-manager:
    desc: "test flamenco container with a sample config"
    dir: deployment/images/manager
    cmds:
      - docker stop my-flamenco-manager-instance || true
      - >
        docker run --rm -p 8090:8080
        --network test-network
        -v ./flamenco-manager.yaml:/server/flamenco-manager.yaml
        -v ./flamenco-manager.sqlite:/server/flamenco-manager.sqlite
        -v ./sample-repository:/repo/
        -d --name my-flamenco-manager-instance flamenco-manager
    silent: true
  run-worker:
    desc: "test flamenco container with a sample config"
    dir: deployment/images/worker
    cmds:
      - docker stop flamenco-worker-instance || true
      - >
        docker run --rm -it
        --network test-network
        -e MANAGER_LOCATION=my-flamenco-manager-instance:8080
        -d --name flamenco-worker-instance flamenco-worker
      - sleep 2
      - docker container logs flamenco-worker-instance --tail all
    silent: true
  debug-job:
    desc: "sends debug job"
    dir: scripts
    cmds:
      - ./debug-job-render.sh
    silent: true

  stop-all:
    cmds:
      - docker stop my-flamenco-manager-instance
      - docker stop flamenco-worker-instance
    silent: true